/**
 * RenderedMarkdown — renders a pre-built HTML chunk for a given slug.
 *
 * Responsibilities:
 * 1. Lazy-loads the HTML chunk via import.meta.glob.
 * 2. Splits the HTML at the "Reading list" h2 section:
 *    - Everything before the reading-list h2 → dangerouslySetInnerHTML
 *    - The reading-list section itself → replaced with <ReadingList slug={slug} />
 *    - Everything after the reading-list section (next h2+) → dangerouslySetInnerHTML
 * 3. Intercepts internal anchor clicks (href starts with /notes/ or /projects/)
 *    and navigates via React Router instead of full reload.
 * 4. Shows a skeleton while loading; a friendly error on failure.
 *
 * Sanitization note: HTML was already sanitized at build time via rehype-sanitize.
 * We do not need DOMPurify at runtime (per spec §17).
 */

import { useEffect, useRef, useCallback } from "react";
import { useNavigate, Link } from "react-router-dom";
import { useTopic } from "@/hooks/useTopic";
import { ReadingList } from "@/components/content/ReadingList";
import { cn } from "@/lib/utils";

// ─── HTML splitting ────────────────────────────────────────────────────────────

interface HtmlSegments {
  before: string; // HTML before the reading-list h2
  hasReadingList: boolean;
  after: string; // HTML after the reading-list section (next h2+)
}

/**
 * Split pre-rendered HTML at the first h2 whose text is "Reading list"
 * (case-insensitive). Returns three segments so React can render the
 * interactive ReadingList component in place of the static section.
 */
function splitAtReadingList(html: string): HtmlSegments {
  // Use DOMParser to find the reading-list h2 and split the document.
  // We work with raw string positions for perf (avoid serializing the whole DOM).

  // Locate the h2 with id="reading-list" (generated by rehype-slug)
  // The pattern produced by the build pipeline looks like:
  //   <h2 id="reading-list"><a ...>Reading list<span ...>...</span></a></h2>
  // We match on id="reading-list" as the stable anchor rather than text.

  // Try to find the h2 element by id attribute
  const h2Pattern = /<h2[^>]*id="reading-list"[^>]*>/i;
  const match = h2Pattern.exec(html);

  if (!match) {
    return { before: html, hasReadingList: false, after: "" };
  }

  const h2Start = match.index;

  // Find the closing </h2> tag
  const h2End = html.indexOf("</h2>", h2Start);
  if (h2End === -1) {
    return { before: html, hasReadingList: false, after: "" };
  }

  const sectionStart = h2Start;

  // Find the next h2 (the end of the reading-list section)
  const afterH2Close = h2End + "</h2>".length;
  const nextH2Pattern = /<h2/i;
  const nextMatch = nextH2Pattern.exec(html.slice(afterH2Close));

  const before = html.slice(0, sectionStart);
  const after = nextMatch
    ? html.slice(afterH2Close + nextMatch.index)
    : "";

  return { before, hasReadingList: true, after };
}

// ─── Internal link interception ───────────────────────────────────────────────

const INTERNAL_PREFIXES = ["/notes/", "/projects/", "/reading", "/about", "/search"];

function isInternalHref(href: string): boolean {
  return INTERNAL_PREFIXES.some((prefix) => href.startsWith(prefix));
}

// ─── Skeleton ─────────────────────────────────────────────────────────────────

function Skeleton() {
  return (
    <div className="space-y-4 animate-pulse" aria-busy="true" aria-label="Loading content">
      <div className="h-8 bg-muted rounded w-3/4" />
      <div className="h-4 bg-muted rounded w-full" />
      <div className="h-4 bg-muted rounded w-5/6" />
      <div className="h-4 bg-muted rounded w-4/5" />
      <div className="h-6 bg-muted rounded w-1/2 mt-8" />
      <div className="h-4 bg-muted rounded w-full" />
      <div className="h-4 bg-muted rounded w-3/4" />
    </div>
  );
}

// ─── HTML content block ───────────────────────────────────────────────────────

interface HtmlBlockProps {
  html: string;
  onNavigate: (path: string) => void;
}

function HtmlBlock({ html, onNavigate }: HtmlBlockProps) {
  const ref = useRef<HTMLDivElement>(null);

  // Intercept internal anchor clicks to use React Router navigation
  useEffect(() => {
    const el = ref.current;
    if (!el) return;

    const handler = (e: MouseEvent) => {
      const target = e.target as HTMLElement;
      const anchor = target.closest("a");
      if (!anchor) return;

      const href = anchor.getAttribute("href");
      if (!href) return;

      // Heading anchor links (#id) — let browser handle scroll
      if (href.startsWith("#")) return;

      // Internal paths → client-side navigation
      if (isInternalHref(href)) {
        e.preventDefault();
        onNavigate(href);
      }
      // External links — default browser behavior (new tab via target="_blank" set at build time)
    };

    el.addEventListener("click", handler);
    return () => el.removeEventListener("click", handler);
  }, [onNavigate]);

  return (
    <div
      ref={ref}
      className={cn("prose")}
      // Sanitized at build time via rehype-sanitize — safe to use dangerouslySetInnerHTML
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}

// ─── Main component ───────────────────────────────────────────────────────────

interface Props {
  slug: string;
  /** Optional extra className on the wrapper */
  className?: string;
}

export function RenderedMarkdown({ slug, className }: Props) {
  const { html, loading, error } = useTopic(slug);
  const navigate = useNavigate();

  const handleNavigate = useCallback(
    (path: string) => {
      navigate(path);
    },
    [navigate]
  );

  if (loading) {
    return (
      <div className={className}>
        <Skeleton />
      </div>
    );
  }

  if (error || !html) {
    return (
      <div
        className={cn(
          "py-10 text-center font-sans text-sm text-muted-foreground space-y-3",
          className
        )}
        role="alert"
      >
        <p className="font-medium text-foreground">Failed to load content.</p>
        <p>
          {error?.message ?? "The page content could not be found."}
        </p>
        <Link
          to="/"
          className="inline-block font-sans text-sm text-primary underline underline-offset-2 hover:no-underline"
        >
          Back to dashboard
        </Link>
      </div>
    );
  }

  const { before, hasReadingList, after } = splitAtReadingList(html);

  return (
    <div className={className}>
      {/* Content before the reading list section */}
      {before && (
        <HtmlBlock html={before} onNavigate={handleNavigate} />
      )}

      {/* Interactive reading list in place of the static rendered section */}
      {hasReadingList && (
        <section aria-label="Reading list">
          {/* Render the h2 heading visually */}
          <h2
            id="reading-list"
            className="text-2xl font-semibold tracking-tight leading-snug text-foreground mt-12 mb-0"
          >
            Reading list
          </h2>
          <ReadingList slug={slug} />
        </section>
      )}

      {/* Content after the reading list section */}
      {after && (
        <HtmlBlock html={after} onNavigate={handleNavigate} />
      )}
    </div>
  );
}
