import { Link } from "react-router-dom";
import { PageContainer } from "@/components/layout/PageContainer";
import { getAllChapters } from "@/lib/textbook";
import { Clock, ArrowRight } from "lucide-react";
import { cn } from "@/lib/utils";

export function TextbookIndexPage() {
  const chapters = getAllChapters();

  return (
    <PageContainer>
      <header className="mb-10">
        <span className="text-2xs font-semibold tracking-wider uppercase text-muted-foreground mb-2 inline-block">
          Textbook · Prerequisites
        </span>
        <h1 className="text-4xl font-semibold tracking-tight text-foreground leading-tight text-balance mb-3">
          Prerequisites
        </h1>
        <p className="text-base text-muted-foreground leading-relaxed max-w-2xl">
          The math and engineering foundations every frontier-LLM topic on this
          site assumes. Calibrated to frontier-model practice as of May 2026.
        </p>
      </header>

      {chapters.length === 0 ? (
        <p className="text-sm text-muted-foreground italic">
          No chapters loaded — content is generated by Phase 3 of the
          textbook delivery. See <code>docs/superpowers/plans/</code>.
        </p>
      ) : (
        <ol className="space-y-3 list-none pl-0">
          {chapters.map((c) => (
            <li key={c.slug}>
              <Link
                to={`/textbook/${c.slug}`}
                className={cn(
                  "group block rounded-md border border-border p-4",
                  "transition-colors duration-150",
                  "hover:bg-subtle/40 focus-visible:outline-2",
                  "focus-visible:outline-ring focus-visible:outline-offset-1",
                )}
              >
                <div className="flex items-start justify-between gap-4">
                  <div className="min-w-0">
                    {c.chapter !== undefined && (
                      <span className="text-2xs font-semibold uppercase tracking-wider text-muted-foreground">
                        Chapter {c.chapter}
                      </span>
                    )}
                    <h2 className="text-lg font-semibold tracking-tight text-foreground mt-1">
                      {c.title}
                    </h2>
                    <p className="text-sm text-muted-foreground mt-1.5 leading-relaxed">
                      {c.description}
                    </p>
                  </div>
                  <div className="flex flex-col items-end gap-2 shrink-0">
                    <span className="inline-flex items-center gap-1 text-2xs text-muted-foreground tabular-nums">
                      <Clock className="w-3 h-3" aria-hidden />
                      {c.reading_minutes} min
                    </span>
                    <ArrowRight
                      className="w-4 h-4 text-muted-foreground group-hover:text-foreground transition-colors"
                      aria-hidden
                    />
                  </div>
                </div>
              </Link>
            </li>
          ))}
        </ol>
      )}
    </PageContainer>
  );
}
